server:
  port: 9091

github:
  user-detail-url: https://api.github.com/repos/EthicalML/awesome-production-machine-learning/contributors

spring:
  data:
    mongodb:
      uri: mongodb+srv://nnimesha97:9a51QdieaGVk43lR@cluster0.sdndqdm.mongodb.net/developer_iq_tracker